apiVersion: v1
kind: Service
metadata:
  name: sb-demo-metrics
  labels:
    app: sb-demo
    app.kubernetes.io/name: sb-demo
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: sb-demo-platform
    app.kubernetes.io/version: "1.0.0"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: sb-demo
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sb-demo-servicemonitor
  labels:
    app: sb-demo
    app.kubernetes.io/name: sb-demo
    app.kubernetes.io/component: service-monitor
    app.kubernetes.io/part-of: sb-demo-platform
    app.kubernetes.io/version: "1.0.0"
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: sb-demo
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - default
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sb-demo-prometheus-rules
  labels:
    app: sb-demo
    app.kubernetes.io/name: sb-demo
    app.kubernetes.io/component: prometheus-rules
    app.kubernetes.io/part-of: sb-demo-platform
    app.kubernetes.io/version: "1.0.0"
    prometheus: kube-prometheus
spec:
  groups:
    - name: sb-demo.rules
      interval: 30s
      rules:
        - alert: SBDemoHighMemoryUsage
          expr: (container_memory_working_set_bytes{pod=~"sb-demo-.*"} / container_spec_memory_limit_bytes{pod=~"sb-demo-.*"}) * 100 > 85
          for: 5m
          labels:
            severity: warning
            service: sb-demo
          annotations:
            summary: "High memory usage detected for Spring Boot Demo"
            description: "Memory usage is above 85% for pod {{ $labels.pod }}"
        
        - alert: SBDemoHighCPUUsage
          expr: (rate(container_cpu_usage_seconds_total{pod=~"sb-demo-.*"}[5m]) / container_spec_cpu_quota{pod=~"sb-demo-.*"} * container_spec_cpu_period{pod=~"sb-demo-.*"}) * 100 > 80
          for: 5m
          labels:
            severity: warning
            service: sb-demo
          annotations:
            summary: "High CPU usage detected for Spring Boot Demo"
            description: "CPU usage is above 80% for pod {{ $labels.pod }}"
        
        - alert: SBDemoApplicationDown
          expr: up{job="sb-demo"} == 0
          for: 1m
          labels:
            severity: critical
            service: sb-demo
          annotations:
            summary: "Spring Boot Demo application is down"
            description: "No instances of sb-demo are reachable"
        
        - alert: SBDemoHighErrorRate
          expr: rate(http_server_requests_seconds_count{status=~"5..", job="sb-demo"}[5m]) / rate(http_server_requests_seconds_count{job="sb-demo"}[5m]) * 100 > 5
          for: 5m
          labels:
            severity: warning
            service: sb-demo
          annotations:
            summary: "High error rate for Spring Boot Demo"
            description: "Error rate is above 5% for the last 5 minutes"