apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sb-demo-eventlistener
  labels:
    app.kubernetes.io/name: sb-demo
    app.kubernetes.io/component: triggers
spec:
  serviceAccountName: sb-demo-pipeline-sa
  triggers:
    - name: github-push-trigger
      interceptors:
        - name: "verify-github-payload"
          ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - name: "filter-main-branch"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/main' || body.ref == 'refs/heads/master'"
      bindings:
        - ref: sb-demo-triggerbinding
      template:
        ref: sb-demo-triggertemplate
    - name: github-pr-trigger
      interceptors:
        - name: "verify-github-payload"
          ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "filter-pr-actions"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: sb-demo-pr-triggerbinding
      template:
        ref: sb-demo-triggertemplate
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: sb-demo-pipeline-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "50m"
                  limits:
                    memory: "128Mi"
                    cpu: "100m"