apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-demo-config
  labels:
    app: sb-demo
    app.kubernetes.io/name: sb-demo
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: sb-demo-platform
    app.kubernetes.io/version: "1.0.0"
data:
  # Application configuration
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  
  # Database configuration (default in-memory for base)
  database-url: "jdbc:derby:memory:sb-demo;create=true"
  
  # JVM configuration
  java-opts: |
    -XX:+UseG1GC
    -XX:MaxRAMPercentage=75.0
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/tmp/heapdump.hprof
    -XX:+ExitOnOutOfMemoryError
    -Djava.security.egd=file:/dev/./urandom
    -Dspring.backgroundpreinitializer.ignore=true
  
  # Spring Boot configuration
  management.endpoints.web.exposure.include: "health,info,metrics,prometheus"
  management.endpoint.health.show-details: "when-authorized"
  management.metrics.export.prometheus.enabled: "true"
  
  # Logging configuration
  logging.level.com.wakefern: "INFO"
  logging.level.org.springframework.web: "INFO"
  logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  # Upload configuration
  upload.max-file-size: "10MB"
  upload.max-request-size: "10MB"
  upload.location: "/app/uploads"
  
  # Error handling
  server.error.whitelabel.enabled: "false"
  server.error.include-stacktrace: "never"
  server.error.include-message: "always"
  
  # Actuator security
  management.server.port: "8080"
  management.security.enabled: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: sb-demo-secrets
  labels:
    app: sb-demo
    app.kubernetes.io/name: sb-demo
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: sb-demo-platform
    app.kubernetes.io/version: "1.0.0"
type: Opaque
data:
  # Default credentials (base64 encoded "sa")
  database-username: c2E=
  database-password: c2E=
stringData:
  # API keys and secrets go here
  # api-key: "your-api-key"
  # jwt-secret: "your-jwt-secret"