apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sb-demo-base
  annotations:
    config.kubernetes.io/local-config: "true"

# Common labels applied to all resources
commonLabels:
  app: sb-demo
  app.kubernetes.io/name: sb-demo
  app.kubernetes.io/part-of: sb-demo-platform
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
  config.kubernetes.io/origin: |
    configuredIn: .k8s/base/kustomization.yaml
    configuredBy:
      apiVersion: builtin
      kind: kustomization

# Resources to include
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - pvc.yaml
  - ingress.yaml

# Image configurations
images:
  - name: sb-demo
    newName: sb-demo
    newTag: latest

# Namespace (can be overridden in overlays)
namespace: default

# ConfigMap and Secret generators
configMapGenerator:
  - name: sb-demo-build-info
    literals:
      - BUILD_TIME=
      - GIT_COMMIT=
      - GIT_BRANCH=
      - BUILD_VERSION=1.0.0
    options:
      disableNameSuffixHash: true

# Resource name prefix (can be overridden)
namePrefix: ""

# Resource name suffix (can be overridden)
nameSuffix: ""

# Replacements for dynamic values
replacements:
  - source:
      kind: ConfigMap
      name: sb-demo-build-info
      fieldPath: data.BUILD_VERSION
    targets:
      - select:
          kind: Deployment
          name: sb-demo
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/version]
          - spec.template.metadata.labels.[app.kubernetes.io/version]
      - select:
          kind: Service
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/version]
      - select:
          kind: ConfigMap
          name: sb-demo-config
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/version]

# Patches for common modifications
patches:
  # Security context patch for non-root containers
  - target:
      kind: Deployment
      name: sb-demo
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext/seccompProfile
        value:
          type: RuntimeDefault
  
  # Add resource quotas labels
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /metadata/labels/storage.kubernetes.io~1managed-by
        value: kustomize

# Generators for additional resources
generators: []

# Transformers
transformers: []

# Validators
validators: []