apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sb-demo-openshift
  annotations:
    config.kubernetes.io/local-config: "true"
    platform.kubernetes.io/target: "openshift"

# Base resources
resources:
  - ../../base
  - route.yaml
  - imagestream.yaml

# Remove Ingress resource as we use OpenShift Routes
patchesJson6902:
  # Remove Ingress resource entirely
  - target:
      version: v1
      kind: Ingress
      name: sb-demo
    path: delete-ingress-patch.yaml

# Strategic merge patches
patchesStrategicMerge:
  - deployment-patch.yaml
  - pvc-patch.yaml

# OpenShift-specific labels
commonLabels:
  platform: openshift

# OpenShift-specific annotations
commonAnnotations:
  openshift.io/generated-by: "kustomize"
  alpha.image.policy.openshift.io/resolve-names: "*"

# Override namespace for OpenShift project
namespace: sb-demo

# Image transformations for OpenShift internal registry
images:
  - name: sb-demo
    newName: image-registry.openshift-image-registry.svc:5000/sb-demo/sb-demo
    newTag: latest

# ConfigMap generator for OpenShift-specific config
configMapGenerator:
  - name: sb-demo-openshift-config
    literals:
      - PLATFORM=openshift
      - OPENSHIFT_BUILD_SOURCE=kustomize
      - CONTAINER_RUNTIME=cri-o
    options:
      disableNameSuffixHash: true

# Additional replacements for OpenShift
replacements:
  - source:
      kind: ConfigMap
      name: sb-demo-openshift-config
      fieldPath: data.PLATFORM
    targets:
      - select:
          kind: Deployment
          name: sb-demo
        fieldPaths:
          - spec.template.metadata.annotations.[platform.kubernetes.io/target]

# Patches for OpenShift-specific security contexts
patches:
  # Remove specific user/group IDs for OpenShift SCC compatibility
  - target:
      kind: Deployment
      name: sb-demo
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext/runAsUser
      - op: remove
        path: /spec/template/spec/securityContext/runAsGroup
      - op: remove
        path: /spec/template/spec/securityContext/fsGroup
      - op: remove
        path: /spec/template/spec/containers/0/securityContext/runAsUser
      - op: remove
        path: /spec/template/spec/containers/0/securityContext/runAsGroup

  # Add OpenShift-specific annotations to Service Account
  - target:
      kind: ServiceAccount
      name: sb-demo
    patch: |-
      - op: add
        path: /metadata/annotations/serviceaccounts.openshift.io~1oauth-redirectreference.primary
        value: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"sb-demo"}}'

  # Configure PVCs for OpenShift
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /metadata/annotations/volume.alpha.kubernetes.io~1storage-class
        value: ""

# Generators for OpenShift-specific resources
generators:
  - generator-options.yaml