apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sb-demo-production
  annotations:
    config.kubernetes.io/local-config: "true"
    environment: "production"

# Base from platform overlay (will be set by deployment script)
resources:
  - ../../base

# Production-specific labels
commonLabels:
  environment: prod
  tier: production

# Production annotations
commonAnnotations:
  environment: "production"
  tier: "prod"
  monitoring: "enabled"
  backup: "enabled"

# Override namespace for production
namespace: sb-demo-prod

# Image for production
images:
  - name: sb-demo
    newName: sb-demo
    newTag: latest

# ConfigMap generator for production configuration
configMapGenerator:
  - name: sb-demo-prod-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - SPRING_PROFILES_ACTIVE=prod
      - LOG_LEVEL=WARN
      - DEBUG_MODE=false
      - ACTUATOR_EXPOSURE=health,info,metrics
      - DATABASE_POOL_SIZE=20
      - ENABLE_SECURITY=true
    options:
      disableNameSuffixHash: true

# Production-specific patches
patches:
  # Production resources
  - target:
      kind: Deployment
      name: sb-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

  # Configure external database for production
  - target:
      kind: ConfigMap
      name: sb-demo-config
    patch: |-
      - op: replace
        path: /data/database-url
        value: "jdbc:postgresql://postgres-prod:5432/sbdemo"

  # Production storage
  - target:
      kind: PersistentVolumeClaim
      name: sb-demo-uploads
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "10Gi"

  - target:
      kind: PersistentVolumeClaim
      name: sb-demo-database
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "20Gi"

  # Production security and monitoring
  - target:
      kind: Deployment
      name: sb-demo
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          value: "20"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MANAGEMENT_SECURITY_ENABLED
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SERVER_ERROR_INCLUDE_STACKTRACE
          value: "never"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
          value: "WARN"

  # Stricter probe settings for production
  - target:
      kind: Deployment
      name: sb-demo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 90
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 45
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/failureThreshold
        value: 5

  # Production affinity rules
  - target:
      kind: Deployment
      name: sb-demo
    patch: |-
      - op: add
        path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
        value:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - sb-demo
            topologyKey: kubernetes.io/hostname

# Replacements for production
replacements:
  - source:
      kind: ConfigMap
      name: sb-demo-prod-config
      fieldPath: data.SPRING_PROFILES_ACTIVE
    targets:
      - select:
          kind: Deployment
          name: sb-demo
        fieldPaths:
          - spec.template.spec.containers/0/env/[name=SPRING_PROFILES_ACTIVE]/value